// <auto-generated />
using System;
using HouseofTutorAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HouseofTutorAPI.Migrations
{
    [DbContext(typeof(HouseofTutorContext))]
    [Migration("20260430090606_FixStudentCourseKey")]
    partial class FixStudentCourseKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HouseofTutorAPI.Models.Course", b =>
                {
                    b.Property<int>("CourseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CourseId"));

                    b.Property<string>("CourseTitle")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("course_title");

                    b.HasKey("CourseId")
                        .HasName("PK__Course__8F1EF7AEB9F1622F");

                    b.ToTable("Course", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("feedback_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<string>("Comment")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("comment");

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("FeedbackDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("feedback_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<int?>("Rating")
                        .HasColumnType("int")
                        .HasColumnName("rating");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("tutor_id");

                    b.HasKey("FeedbackId")
                        .HasName("PK__Feedback__7A6B2B8C35A2CDED");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("Feedback", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Request", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("request_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestId"));

                    b.Property<int?>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<DateTime?>("RequestDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime")
                        .HasColumnName("request_date")
                        .HasDefaultValueSql("(getdate())");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("tutor_id");

                    b.HasKey("RequestId")
                        .HasName("PK__Request__18D3B90F519F4A7A");

                    b.HasIndex("CourseId");

                    b.HasIndex("StudentId");

                    b.HasIndex("TutorId");

                    b.ToTable("Request", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Schedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("Day")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("day");

                    b.Property<string>("Time")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("time");

                    b.Property<int?>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("tutor_id");

                    b.HasKey("ScheduleId")
                        .HasName("PK__Schedule__C46A8A6FEF990444");

                    b.HasIndex("TutorId");

                    b.ToTable("Schedule", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Student", b =>
                {
                    b.Property<int>("StudentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StudentId"));

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("StudentId")
                        .HasName("PK__Student__2A33069A6C1D77D6");

                    b.HasIndex("UserId");

                    b.ToTable("Student", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.StudentCourse", b =>
                {
                    b.Property<int>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.HasKey("StudentId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Student_Course", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.StudentSchedule", b =>
                {
                    b.Property<int>("ScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("schedule_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ScheduleId"));

                    b.Property<string>("Day")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("day");

                    b.Property<int?>("StudentId")
                        .HasColumnType("int")
                        .HasColumnName("student_id");

                    b.Property<string>("Time")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("time");

                    b.HasKey("ScheduleId");

                    b.HasIndex("StudentId");

                    b.ToTable("Student_Schedule", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Tutor", b =>
                {
                    b.Property<int>("TutorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tutor_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TutorId"));

                    b.Property<int?>("Experience")
                        .HasColumnType("int")
                        .HasColumnName("experience");

                    b.Property<double?>("Latitude")
                        .HasColumnType("float");

                    b.Property<string>("Location")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("location");

                    b.Property<double?>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Qualification")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("qualification");

                    b.Property<int?>("Radius")
                        .HasColumnType("int")
                        .HasColumnName("radius");

                    b.Property<string>("Status")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("status");

                    b.Property<int?>("UserId")
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    b.HasKey("TutorId")
                        .HasName("PK__Tutor__50DE5D0142BF8F72");

                    b.HasIndex("UserId");

                    b.ToTable("Tutor", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.TutorCourse", b =>
                {
                    b.Property<int>("TutorId")
                        .HasColumnType("int")
                        .HasColumnName("tutor_id");

                    b.Property<int>("CourseId")
                        .HasColumnType("int")
                        .HasColumnName("course_id");

                    b.Property<string>("Grade")
                        .HasMaxLength(10)
                        .IsUnicode(false)
                        .HasColumnType("varchar(10)")
                        .HasColumnName("grade");

                    b.HasKey("TutorId", "CourseId")
                        .HasName("PK__Tutor_Co__A82FB27BA4857372");

                    b.HasIndex("CourseId");

                    b.ToTable("Tutor_Course", (string)null);
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("user_id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Cnic")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("cnic");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("full_name");

                    b.Property<string>("Password")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("password");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("role");

                    b.HasKey("UserId")
                        .HasName("PK__Users__B9BE370FAAD384A7");

                    b.HasIndex(new[] { "Email" }, "UQ__Users__AB6E6164B2DCE846")
                        .IsUnique()
                        .HasFilter("[email] IS NOT NULL");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Feedback", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.Course", "Course")
                        .WithMany("Feedbacks")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Feedback__course__66603565");

                    b.HasOne("HouseofTutorAPI.Models.Student", "Student")
                        .WithMany("Feedbacks")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Feedback__studen__6477ECF3");

                    b.HasOne("HouseofTutorAPI.Models.Tutor", "Tutor")
                        .WithMany("Feedbacks")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__Feedback__tutor___656C112C");

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Request", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.Course", "Course")
                        .WithMany("Requests")
                        .HasForeignKey("CourseId")
                        .HasConstraintName("FK__Request__course___5FB337D6");

                    b.HasOne("HouseofTutorAPI.Models.Student", "Student")
                        .WithMany("Requests")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK__Request__student__5DCAEF64");

                    b.HasOne("HouseofTutorAPI.Models.Tutor", "Tutor")
                        .WithMany("Requests")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__Request__tutor_i__5EBF139D");

                    b.Navigation("Course");

                    b.Navigation("Student");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Schedule", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.Tutor", "Tutor")
                        .WithMany("Schedules")
                        .HasForeignKey("TutorId")
                        .HasConstraintName("FK__Schedule__tutor___5629CD9C");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Student", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.User", "User")
                        .WithMany("Students")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Student__user_id__5165187F");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.StudentCourse", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.Course", "Course")
                        .WithMany("StudentCourses")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HouseofTutorAPI.Models.Student", "Student")
                        .WithMany("StudentCourses")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.StudentSchedule", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.Student", "Student")
                        .WithMany("StudentSchedules")
                        .HasForeignKey("StudentId")
                        .HasConstraintName("FK_StudentSchedule_Student");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Tutor", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.User", "User")
                        .WithMany("Tutors")
                        .HasForeignKey("UserId")
                        .HasConstraintName("FK__Tutor__user_id__4E88ABD4");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.TutorCourse", b =>
                {
                    b.HasOne("HouseofTutorAPI.Models.Course", "Course")
                        .WithMany("TutorCourses")
                        .HasForeignKey("CourseId")
                        .IsRequired()
                        .HasConstraintName("FK__Tutor_Cou__cours__59FA5E80");

                    b.HasOne("HouseofTutorAPI.Models.Tutor", "Tutor")
                        .WithMany("TutorCourses")
                        .HasForeignKey("TutorId")
                        .IsRequired()
                        .HasConstraintName("FK__Tutor_Cou__tutor__59063A47");

                    b.Navigation("Course");

                    b.Navigation("Tutor");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Course", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Requests");

                    b.Navigation("StudentCourses");

                    b.Navigation("TutorCourses");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Student", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Requests");

                    b.Navigation("StudentCourses");

                    b.Navigation("StudentSchedules");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.Tutor", b =>
                {
                    b.Navigation("Feedbacks");

                    b.Navigation("Requests");

                    b.Navigation("Schedules");

                    b.Navigation("TutorCourses");
                });

            modelBuilder.Entity("HouseofTutorAPI.Models.User", b =>
                {
                    b.Navigation("Students");

                    b.Navigation("Tutors");
                });
#pragma warning restore 612, 618
        }
    }
}
